### PR TITLE
Bug in creating parent directories causing failure of copy/renaming of m3u8

### PR DESCRIPTION
**Pull request by cjcolvar**
@mikedurbin Could you review this?

### CODE REVIEW

**Comment by mikedurbin** [comment]
Yeah, I'd be happy to take a look at it.  

While the code change and the error that would occur seem self-evident, is there a set of conditions or configuration changes that resulted in failure?  Is there a tell-tale stack trace in the logs when this fix isn't in place?

**Comment by cjcolvar** [comment]
I think this is the stacktrace associated with this PR, but it came from another user.
https://gist.github.com/cjcolvar/a7ead7472e9ffd6673f1

**Comment by mikedurbin** [comment]
@cjcolvar , While I can't reproduce the error, I was able to verify that this code doesn't break the tests and didn't appear to introduce any issues when used within matterhorn processing a batch for Avalon.

I have no qualms with you merging this PR.

**Comment by cjcolvar** [comment]
@shfarr @mikedurbin I'll build a branch of avalon-felix with this patch integrated for you to test out, but it will be a few days until I can do that.  This isn't going to make it into Avalon 4.0 proper, but that shouldn't stop you from installing and running it.  I'll plan on writing up some instructions for doing that.

**Comment by shfarr** [comment]
@cjcolvar,

Thank you very much for your promptness. The issue does not present an
urgency any more, as we solved it by re-installing, reconfiguring the
server and fiddling with the versions from the install config file.The
truth is we are not entirely certain how we solved the issue :), but it
works.

I have been watching the communication on this and it is very probable that
normally that piece of code would be avoided. The error is real, as I
extracted the piece of code and tested the behavior, but I believe that
under normal circumstances the directory is created somewhere before
entering that entire block of code and so that "IF" block is normally
skipped. We suspect it might have to do with symbolic links in the
installation path, but I am not familiar with Avalon, I only started
debugging it because the client reported the error and they needed it fixed
urgently. I found the root of *their* problem and I escalated it to you
guys.

At this point it is fine if it gets into the code at any version in the
future, we will grab it within an upgrade session.
BTW: although not urgent, some documentation/tutorial on the installation
would definitely be useful.

Thanks again for your promptness and helpfulness.

Best regards,
Stefan
~~~



On Tue, Aug 4, 2015 at 6:04 PM, cjcolvar <notifications@github.com> wrote:

> @shfarr <https://github.com/shfarr> @mikedurbin
> <https://github.com/mikedurbin> I'll build a branch of avalon-felix with
> this patch integrated for you to test out, but it will be a few days until
> I can do that. This isn't going to make it into Avalon 4.0 proper, but that
> shouldn't stop you from installing and running it. I'll plan on writing up
> some instructions for doing that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/avalonmediasystem/matterhorn-distribution-service-hls/pull/2#issuecomment-127643289>
> .
>

**Pull request merged**
